Bag of words

In [ ]:
import numpy as np
import pandas as pd


In [ ]:
df=pd.DataFrame({"text":["people watch dswithbappy",
                         "dswithbappy watch dswithbappy",
                         "people write comment",
                          "dswithbappy write comment"],"output":[1,1,0,0]}) # if there watch dswithbappy means 1 , write comment means 0

In [ ]:
df

text  output
0       people watch dswithbappy       1
1  dswithbappy watch dswithbappy       1
2           people write comment       0
3      dswithbappy write comment       0

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer()
bow=cv.fit_transform(df['text'])


In [ ]:
print(cv.vocabulary_)

{'people': 2, 'watch': 3, 'dswithbappy': 1, 'write': 4, 'comment': 0}


In [ ]:
bow.toarray()

array([[0, 1, 1, 1, 0],
       [0, 2, 0, 1, 0],
       [1, 0, 1, 0, 1],
       [1, 1, 0, 0, 1]])

In [ ]:
cv.transform(['anwar watch dswithbappy']).toarray()

array([[0, 1, 0, 1, 0]])

N Grams

In [ ]:
df

text  output
0       people watch dswithbappy       1
1  dswithbappy watch dswithbappy       1
2           people write comment       0
3      dswithbappy write comment       0

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(ngram_range=(2,2))

bow=cv.fit_transform(df['text'])

# from sklearn.feature_extraction.text import CountVectorizer

# # Example for unigrams (default)
# vectorizer = CountVectorizer(ngram_range=(1,1))

# # For unigrams and bigrams
# vectorizer = CountVectorizer(ngram_range=(1,2))

# # For only bigrams
# vectorizer = CountVectorizer(ngram_range=(2,2))

# # For unigrams, bigrams, and trigrams
# vectorizer = CountVectorizer(ngram_range=(1,3))


In [ ]:
print(cv.vocabulary_)

{'people watch': 2, 'watch dswithbappy': 4, 'dswithbappy watch': 0, 'people write': 3, 'write comment': 5, 'dswithbappy write': 1}


In [ ]:
print(bow.toarray())

[[0 0 1 0 1 0]
 [1 0 0 0 1 0]
 [0 0 0 1 0 1]
 [0 1 0 0 0 1]]


TF-IDF (Term frequency inverse document frequecy)

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf=TfidfVectorizer()


In [ ]:
arr=tfidf.fit_transform(df['text']).toarray()

In [ ]:
print(arr)

[[0.         0.49681612 0.61366674 0.61366674 0.        ]
 [0.         0.8508161  0.         0.52546357 0.        ]
 [0.57735027 0.         0.57735027 0.         0.57735027]
 [0.61366674 0.49681612 0.         0.         0.61366674]]


Word 2 vec


In [ ]:
 ## Download the game of thrones book from kaggle


In [ ]:
# gensim where word 2 vec is available
!pip install --upgrade gensim --user

In [ ]:
import numpy as np
import pandas as pd
import gensim
import os

In [ ]:
from nltk import sent_tokenize
from gensim.utils import simple_preprocess
import nltk
nltk.download("punkt")


[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


True

In [ ]:
from nltk import corpus

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


After mounting your drive, you can access your text file. Replace `'path/to/your/textfile.txt'` with the actual path to your file in Google Drive.

In [ ]:
nltk.download("punkt_tab")
file_path = '/content/drive/MyDrive/Colab Notebooks/Game of Thrones book.txt'

story=[]
f=open(file_path,'r',encoding='utf-8')
corpus=f.read()
sentences=sent_tokenize(corpus)
for i in sentences:
  story.append(simple_preprocess(i))

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.


In [ ]:
story[0]

['game',
 'of',
 'thrones',
 'book',
 'one',
 'of',
 'song',
 'of',
 'ice',
 'and',
 'fire',
 'by',
 'george',
 'martin',
 'prologue',
 'we',
 'should',
 'start',
 'back',
 'gared',
 'urged',
 'as',
 'the',
 'woods',
 'began',
 'to',
 'grow',
 'dark',
 'around',
 'them']

In [ ]:
model=gensim.models.Word2Vec(
    window=10,
    min_count=2,
)

In [ ]:
model.build_vocab(story)

In [ ]:
model.train(story,total_examples=model.corpus_count,epochs=model.epochs)

(1058227, 1423500)

In [ ]:
model.wv.most_similar('daenerys')

[('eunuch', 0.9967272281646729),
 ('halder', 0.9951837658882141),
 ('tarly', 0.9950230717658997),
 ('fat', 0.9949220418930054),
 ('rider', 0.9948598742485046),
 ('nine', 0.994811475276947),
 ('riding', 0.9946297407150269),
 ('animal', 0.9944400787353516),
 ('cook', 0.9942600727081299),
 ('meal', 0.9940683245658875)]

In [ ]:
model.wv.similarity('daenerys','jon')

0.78437275

In [ ]:
model.wv['jon'].shape

(100,)

In [ ]:
vec=model.wv.get_normed_vectors()

In [ ]:
vec

array([[-0.04528382,  0.0335387 , -0.02894359, ..., -0.10738726,
        -0.00348531,  0.13059445],
       [-0.03872854,  0.11430094, -0.00995462, ..., -0.16958505,
         0.0654107 ,  0.0644033 ],
       [-0.17524754,  0.06396016,  0.03654763, ..., -0.08879431,
         0.06272236, -0.12019772],
       ...,
       [-0.07227376, -0.02298464,  0.02911904, ..., -0.17951824,
         0.04317986, -0.07664339],
       [-0.00725828,  0.05343652,  0.02773437, ..., -0.15932599,
         0.01108546, -0.01880511],
       [ 0.0065358 ,  0.11378384,  0.00729819, ..., -0.16024476,
         0.05996841, -0.05580611]], dtype=float32)

In [ ]:
# we need to reduce the dimension to 3 dimension

In [ ]:
from sklearn.decomposition import PCA
pca=PCA(n_components=3)
X=pca.fit_transform(vec)
X

array([[-0.38694578,  0.19444364, -0.25013772],
       [-0.47560808,  0.10409635, -0.20337313],
       [ 0.43540633,  0.09652543, -0.02255872],
       ...,
       [ 0.29870465,  0.07856441,  0.20380956],
       [-0.27276   , -0.03114885, -0.06894591],
       [-0.06962159,  0.0192166 ,  0.12486812]], dtype=float32)

In [ ]:
import plotly.express as px
fig=px.scatter_3d(X[200:300],x=0,y=1,z=2,color=y[200:300])
fig.show()

NameError: name 'y' is not defined